[workspace]
members = [
    "examples/account-management",
    "sealevel-tools"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/rtrombone/safer-solana"
rust-version = "1.75.0"
version = "0.2.0-beta.1"

[workspace.dependencies]
bincode = "1.3.3"
borsh = "1.5.1"
const-crypto = "0.3"
sealevel-tools = { path = "sealevel-tools" }
solana-banks-interface = "=2.0"
solana-program = "=2.0"
solana-program-test = "=2.0"
solana-sdk = "=2.0"
spl-discriminator = "0.3"
spl-token = { version = "6.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "5.0", features = ["no-entrypoint"] }
thiserror = "1.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
