[package]
name = "sealevel-tools"
description = "Placeholder for real crate"

edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["borsh", "token"]
borsh = ["dep:borsh"]
token = ["dep:spl-token-2022"]

[dependencies]
borsh = { optional = true, workspace = true }
const-crypto.workspace = true
solana-program.workspace = true
spl-token-2022 = { optional = true, workspace = true }
thiserror.workspace = true

[dev-dependencies]
anchor-lang.workspace = true
spl-discriminator.workspace = true
