[package]
name = "sealevel-tools"
description = "Placeholder for real crate"

edition = "2021"
license = "MIT"
rust-version = "1.75.0"
version = "0.0.1"

[features]
default = ["borsh"]
borsh = ["dep:borsh"]

[dependencies]
borsh = { optional = true, version = "1.5.1" }
const-crypto = "0.3.0"

[dev-dependencies]
anchor-lang = "0.30.1"
spl-discriminator = "0.3.0"
