[package]
name = "sealevel-tools"
description = "Tools for Solana program development"
keywords = [
    "solana",
    "solana-program",
    "spl",
    "anchor-lang"
]

edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["borsh"]
borsh = ["dep:borsh"]
token = [
    "dep:spl-token",
    "dep:spl-token-2022"
]

[dependencies]
borsh = { optional = true, workspace = true }
const-crypto.workspace = true
solana-program.workspace = true
spl-token = { optional = true, workspace = true }
spl-token-2022 = { optional = true, workspace = true }
thiserror.workspace = true

[dev-dependencies]
anchor-lang.workspace = true
spl-discriminator.workspace = true
